// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClj06NfyeX0bNtYMyh4SpO27YKhiq5IvA',
    appId: '1:981138852988:web:8f68b35219b350f347cdf9',
    messagingSenderId: '981138852988',
    projectId: 'solution-challenge-595de',
    authDomain: 'solution-challenge-595de.firebaseapp.com',
    storageBucket: 'solution-challenge-595de.firebasestorage.app',
    measurementId: 'G-NZ9N6YXTNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs0UzjsXrnJ61gW7tCZ4HLOwFCqUqz8Qs',
    appId: '1:981138852988:android:2db8c9b70f61e58547cdf9',
    messagingSenderId: '981138852988',
    projectId: 'solution-challenge-595de',
    storageBucket: 'solution-challenge-595de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCESqD_Jo0eIa7IF92K8NbQPQkO2lD19JI',
    appId: '1:981138852988:ios:873838795820f8ce47cdf9',
    messagingSenderId: '981138852988',
    projectId: 'solution-challenge-595de',
    storageBucket: 'solution-challenge-595de.firebasestorage.app',
    iosBundleId: 'com.example.googleSolutionChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCESqD_Jo0eIa7IF92K8NbQPQkO2lD19JI',
    appId: '1:981138852988:ios:873838795820f8ce47cdf9',
    messagingSenderId: '981138852988',
    projectId: 'solution-challenge-595de',
    storageBucket: 'solution-challenge-595de.firebasestorage.app',
    iosBundleId: 'com.example.googleSolutionChallenge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClj06NfyeX0bNtYMyh4SpO27YKhiq5IvA',
    appId: '1:981138852988:web:a25989c167858e2247cdf9',
    messagingSenderId: '981138852988',
    projectId: 'solution-challenge-595de',
    authDomain: 'solution-challenge-595de.firebaseapp.com',
    storageBucket: 'solution-challenge-595de.firebasestorage.app',
    measurementId: 'G-ELSLM42C1C',
  );
}
